# Generated by Django 4.1.3 on 2022-11-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livros_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Devolução'),
        ),
    ]
