# Generated by Django 4.1.3 on 2022-11-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
