# Generated by Django 4.1.3 on 2022-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_rename_emprestimo_emprestimos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
