# Generated by Django 4.1.1 on 2022-12-27 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0021_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 10, 15, 24, 994559)),
        ),
    ]
